<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RandomSimulator\RandomSimulator.csproj" />
    <ProjectReference Include="..\Instruments\Instruments.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NodaTime" Version="3.3.2" />
  </ItemGroup>

</Project>
